### ISSUE TITLE
ModuleNotFoundError: No module named 'eth_account._utils.transactions'

### ISSUE THREAD

**Issue by poor-defined** [Conflux-Chain/python-conflux-sdk#1]
```
Traceback (most recent call last):
  File "/Users/zhousiyuan/Documents/learn_cfx/python_sdk/connection.py", line 1, in <module>
    from conflux import (
  File "/opt/anaconda3/lib/python3.8/site-packages/conflux/__init__.py", line 15, in <module>
    from cfx_account import Account
  File "/opt/anaconda3/lib/python3.8/site-packages/cfx_account/__init__.py", line 1, in <module>
    from cfx_account.account import Account
  File "/opt/anaconda3/lib/python3.8/site-packages/cfx_account/account.py", line 20, in <module>
    from cfx_account._utils.signing import (
  File "/opt/anaconda3/lib/python3.8/site-packages/cfx_account/_utils/signing.py", line 1, in <module>
    from .transactions import (
  File "/opt/anaconda3/lib/python3.8/site-packages/cfx_account/_utils/transactions.py", line 21, in <module>
    from eth_account._utils.transactions import (
ModuleNotFoundError: No module named 'eth_account._utils.transactions'
```

**Comment by poor-defined** [comment]
![image](https://user-images.githubusercontent.com/85155313/136784171-651205ee-e3c5-49af-b44a-02db6f377caa.png)
I had fixed this bug here

**Comment by woshiwenquan** [comment]
it's work

**Comment by Pana** [comment]
Should use "eth-account>=0.5.3,<=0.5.4"

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/
